apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: hello-frontend
spec:
  type: LoadBalancer
  selector:
    app: hello-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
